server:
  port: 8087
spring:
  redis:
      host: 47.99.84.178
      password: 147258369
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1